added crumbles
acm-ucr/starlight-legacy pull request #64
Opened 2024-11-05 02:58 UTC by Shadow-The-Dark-Knight

![image](https://github.com/user-attachments/assets/ac79ffdf-2269-4b5e-a063-d8d0cd04b209)

2024-11-05 03:51 UTC, seanquiambao requested changes

2024-11-05 03:51 UTC, seanquiambao commented on src/app/admin/[program]/page.tsx
> +              <BreadcrumbSeparator />
should be a program name like ignite or create, not forms.

2024-11-05 03:51 UTC, seanquiambao commented on src/app/admin/[program]/page.tsx
> +              <BreadcrumbSeparator />
<img width="263" alt="image" src="https://github.com/user-attachments/assets/6198ee65-316e-47b1-a675-d424a875e369">

remove excess separator

2024-11-05 04:46 UTC, Shadow-The-Dark-Knight commented on src/app/admin/[program]/page.tsx
> +              <BreadcrumbSeparator />
![image](https://github.com/user-attachments/assets/8030fd13-e082-4a89-bbfc-bb52377ac82c)

2024-11-06 10:01 UTC, shahdivyank commented on src/app/admin/[program]/page.tsx
> +                <BreadcrumbLink href="/form">Ignite</BreadcrumbLink>
should not point to form

2024-11-06 10:01 UTC, shahdivyank commented on src/app/admin/[program]/page.tsx
> +                  href={`/form/`}
should not point to form

2024-11-06 10:01 UTC, shahdivyank commented on src/app/admin/[program]/page.tsx
> +                ></BreadcrumbLink>
should contain text, check the issue requirements

2024-11-06 10:01 UTC, shahdivyank commented on src/app/form/[role]/page.tsx
> +            <BreadcrumbSeparator>
breadcrumbs should only be applied to one page, check the issue requirements

2024-11-17 21:25 UTC, closed without merging