#62 AnPhu-D/application page icons
acm-ucr/starlight-legacy pull request #66
Opened 2024-11-07 01:21 UTC by AnPhu-D

Add icons to /public/icons
Change icon src refs in toolbar.tsx

2024-11-07 21:41 UTC, AnPhu-D commented
![image](https://github.com/user-attachments/assets/e1f0b93b-b8be-4606-9b8a-b9dc2a2b76fa)

2024-11-08 03:24 UTC, khandrew1 requested changes

2024-11-08 03:24 UTC, khandrew1 commented on src/components/global/table/toolbar.tsx
> +        <img src="/icons/refresh.svg" alt="Refresh" className="h-6 w-6" />
find the icons using the lucid library instead of svgs

2024-11-08 04:00 UTC, khandrew1 requested changes

2024-11-08 04:00 UTC, khandrew1 commented on src/components/global/table/toolbar.tsx
> +      <div className="cursor-pointer">
instead of using `cursor-pointer`, just make these buttons as we have to add functionality to it at some point.

2024-11-08 04:09 UTC, closed without merging